name: Build Test

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Project_File: ActiveDirectoryQuerier\ActiveDirectoryQuerier.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '8.0.x'

    - name: Install Active Directory Module
      run: |
        Install-WindowsFeature RSAT-AD-PowerShell
        Import-Module ActiveDirectory

    - name: Dotnet Restore & Build
      run: dotnet build $env:Project_File -c Debug -f net8.0-windows -r win-${{ matrix.targetplatform }}

    - name: Dotnet Test with Coverage
      run: |
        dotnet test $env:Project_File --no-build
