name: Built Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
        #targetplatform: [x86, x64]

    runs-on: windows-latest

    env:
      Project_File: FAFB-PowerShell-Tool\FAFB-PowerShell-Tool.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Dotnet Restore & Build
      run: dotnet build $env:Project_File -c Debug -f net6.0-windows -r win-${{ matrix.targetplatform }}

    - name: Dotnet Test
      run: dotnet test
