name: .NET Core Desktop .EXE (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86, x64]

    runs-on: windows-latest

    env:
      Project_File: FAFB-PowerShell-Tool\FAFB-PowerShell-Tool.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build $env:Project_File -c Release -f net8.0-windows -r win-${{ matrix.targetplatform }} --self-contained true

    - name: Publish Artifact
      run: dotnet publish -c Release -f net8.0-windows -r win-${{ matrix.targetplatform }} -o ./FAFB_PowerShell_Tool_${{ matrix.targetplatform }} --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=embedded

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FAFB_PowerShell_Tool_${{ matrix.targetplatform }}
        path: FAFB_PowerShell_Tool_${{ matrix.targetplatform }}
