name: .NET Core Desktop - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
        #targetplatform: [x86, x64]

    runs-on: windows-latest
    env:
      Project_File: FAFB-PowerShell-Tool\FAFB-PowerShell-Tool.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Dotnet Build & Publish
      run: |
        dotnet restore
        dotnet build $env:Project_File -c Release -f net8.0-windows -r win-${{ matrix.targetplatform }} --no-restore
        dotnet publish $env:Project_File -c Release -f net8.0-windows -r win-${{ matrix.targetplatform }} -o ./FAFB_PowerShell_Tool_${{ matrix.targetplatform }} --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FAFB_PowerShell_Tool_${{ matrix.targetplatform }}
        path: FAFB_PowerShell_Tool_${{ matrix.targetplatform }}
