name: Create and Upload Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
        #targetplatform: [x86, x64]

    runs-on: windows-latest

    env:
      Project_File: ActiveDirectoryQuerier\ActiveDirectoryQuerier.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Dotnet Build & Publish
      run: |
        dotnet build $env:Project_File -c Release -f net8.0-windows -r win-${{ matrix.targetplatform }}
        dotnet publish $env:Project_File -c Release -f net8.0-windows -r win-${{ matrix.targetplatform }} -o ./publish/ActiveDirectoryQuerier_${{ matrix.targetplatform }}

    - name: Zip Release Files
      run: Compress-Archive -Path .\publish\ActiveDirectoryQuerier_${{ matrix.targetplatform }} -DestinationPath .\ActiveDirectoryQuerier_${{ matrix.targetplatform }}.zip

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ActiveDirectoryQuerier_${{ matrix.targetplatform }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
